# Generated by Django 4.2.5 on 2023-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyMonthTicket",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("license_plate", models.CharField(max_length=15)),
                ("time_buy", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("expired", models.DateTimeField()),
            ],
        ),
    ]
