# Generated by Django 4.2.5 on 2023-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=15)),
                ("time_in", models.DateTimeField()),
                ("time_out", models.DateTimeField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
