# Generated by Django 4.2.5 on 2023-12-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0002_carmanagement_plate_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmanagement",
            name="time_in",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="carmanagement",
            name="time_out",
            field=models.DateTimeField(null=True),
        ),
    ]
