# Generated by Django 4.2.5 on 2023-12-18 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camera", "0003_alter_carmanagement_time_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmanagement",
            name="price",
        ),
    ]
