# Generated by Django 4.2.5 on 2023-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("total_payments", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_vehicles_in", models.IntegerField(default=0)),
                ("total_vehicles_out", models.IntegerField(default=0)),
                ("total_monthly_subscriptions", models.IntegerField(default=0)),
                ("active_monthly_subscriptions", models.IntegerField(default=0)),
            ],
        ),
    ]
