# Generated by Django 4.2.5 on 2023-10-18 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EditInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rtsp_in", models.CharField(default="0", max_length=100, unique=True)),
                (
                    "rtsp_out",
                    models.CharField(default="0", max_length=100, unique=True),
                ),
                (
                    "rtsp_zone",
                    models.CharField(default="0", max_length=100, unique=True),
                ),
                ("month_price", models.IntegerField(default=1000000)),
                ("day_price1", models.IntegerField(default=30000)),
                (
                    "time_day1",
                    models.DateTimeField(
                        default=datetime.datetime(
                            1999, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "time_day2",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2000, 1, 1, 11, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
