# Generated by Django 4.2.5 on 2023-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editinfor",
            name="day_price2",
            field=models.IntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name="editinfor",
            name="day_price1",
            field=models.IntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name="editinfor",
            name="time_day1",
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="editinfor",
            name="time_day2",
            field=models.IntegerField(default=18),
        ),
    ]
